defaults:
  - _self_

method: semi-supervised-ensemble

train:
  total_epochs: 250
  validation_interval: 10

init:
  _target_: trainer.SemiSupervisedEnsemble
  supervised_criterion:
    _target_: torch.nn.MSELoss
  consistency_criterion:
    _target_: torch.nn.MSELoss
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    _target_: schedulers.build_warmup_cosine
    _partial_: true
    warmup_epochs: 10
    total_epochs:  ${trainer.train.total_epochs}
    warmup_start_factor: 0.1
    eta_min: 1e-5
  ema_decay: 0.999
  max_consistency_weight: 10.0
  rampup_epochs: 80

    